### ISSUE TITLE
Trained Weights

### ISSUE THREAD

**Issue by hamid-mp** [JoyeBright/DeepSentiPers#31]
Hi, Thanks for sharing your awesome code, could you please share the **weights** of your model? where can I find the dataset that you used? as I see, you've partitioned the data to `original.csv`, `balanced.csv`, and `translation.csv`. so how can I get it? Thanks in Advance

**Comment by JoyeBright** [comment]
Thanks for reaching out. Datasets are available under "Dataset": https://github.com/JoyeBright/DeepSentiPers/tree/master/Dataset.
Regarding models' weights, AFAIK, we did not release them, but implementations are there to help you reproduce the approximation results. I am tagging @parsa-abbasi; he might want to add something to your inquiry.

**Comment by hamid-mp** [comment]
Thanks a lot,
